# Generated by Django 4.2.16 on 2025-11-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispatch_name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Диспетчерское наименование",
                    ),
                ),
                (
                    "pf_name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Наименование в PowerFactory",
                    ),
                ),
                ("current_capacity", models.FloatField(verbose_name="ДДТН, А")),
                ("length", models.FloatField(verbose_name="Длина ЛЭП, км")),
                (
                    "manual_ct_ratio",
                    models.FloatField(verbose_name="Номинальный ток ТТ"),
                ),
                (
                    "manual_vt_ratio",
                    models.FloatField(verbose_name="Номинальное напряжение ТН"),
                ),
                (
                    "branch_count",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Количество ответвлений",
                    ),
                ),
                (
                    "is_offset_applied",
                    models.BooleanField(
                        default=False,
                        verbose_name="Применение смещения в защищаемую зону",
                    ),
                ),
                (
                    "zero_sequence_voltage",
                    models.FloatField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Составляющая напряжения нулевой последовательности",
                    ),
                ),
                (
                    "offset_coefficient",
                    models.FloatField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Коэффициент смещения для ЛЭП",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineTap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispatch_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Диспетчерское наименование ответвления",
                    ),
                ),
                (
                    "pf_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Наименование в PowerFactory",
                    ),
                ),
                ("length", models.FloatField(verbose_name="Длина ответвления")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активно ли ответвление"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Наименование типа ЛЭП",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Substation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispatch_name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Диспетчерское наименование",
                    ),
                ),
                (
                    "pf_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Наименование в PowerFactory",
                    ),
                ),
                (
                    "voltage_level",
                    models.FloatField(verbose_name="Уровень напряжения, кВ"),
                ),
            ],
        ),
    ]
