# Generated by Django 4.2.16 on 2025-11-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="line",
            name="current_capacity",
            field=models.FloatField(default=2000, verbose_name="ДДТН, А"),
        ),
        migrations.AlterField(
            model_name="line",
            name="manual_ct_ratio",
            field=models.FloatField(default=2000, verbose_name="Номинальный ток ТТ"),
        ),
        migrations.AlterField(
            model_name="line",
            name="manual_vt_ratio",
            field=models.FloatField(
                default=2200, verbose_name="Номинальное напряжение ТН"
            ),
        ),
    ]
